[tools]
kind = "0.27.0"

[env]
# keep-sorted start
CLUSTER_FQDN = "kind02.internal"
CLUSTER_NAME = "kind02"
# keep-sorted end

[tasks."create:kind02-internal"]
description = 'Create K8s cluster'
run = '${CLUSTERS_RUN_SCRIPT_DIRECTORY}/run-kind.sh create'

[tasks."delete:kind02-internal"]
description = 'Delete K8s cluster'
run = '${CLUSTERS_RUN_SCRIPT_DIRECTORY}/run-kind.sh delete'
